package com.example.timeassistant.entity;


// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import com.litesuits.orm.db.annotation.Column;
import com.litesuits.orm.db.annotation.PrimaryKey;
import com.litesuits.orm.db.annotation.Unique;
import com.litesuits.orm.db.enums.AssignType;
import com.zkteco.android.framework.db.liteorm.db.annotation.Table;

@Table("ScheduleDepartment")
public class ScheduleDepartment extends BaseScheduleItem {
    public static final String COL_DEPTID = "deptId";
    public static final String COL_DEPTNAME = "deptName";
    public static final String COL_ISSELECT = "isSelect";
    public static final String COL_SHIFTID = "shiftId";
    public static final String COL_DEVICESN = "deviceSn";
    public static final String COL_IDANDDEVICESN = "idAndDeviceSn";

    @PrimaryKey(AssignType.BY_MYSELF)
    @Column(COL_IDANDDEVICESN)
    @Unique
    private String idAndDeviceSn;   //liteOrm 找不到联合主键的用法 ，所以添加该字段用作主键 格式是：“deptId-devicesn”
    @Column(COL_DEPTID)
    private long deptId;
    @Column(COL_DEPTNAME)
    private String deptName;
    @Column(COL_ISSELECT)
    private boolean isSelect;
    @Column(COL_SHIFTID)
    private int shiftId;
    @Column(COL_DEVICESN)
    private String deviceSn;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ScheduleDepartment() {
    }

    public ScheduleDepartment(long deptId) {
        this.deptId = deptId;
    }

    public ScheduleDepartment(long deptId, String deptName, boolean isSelect, int shiftId, String deviceSn) {
        this.deptId = deptId;
        this.deptName = deptName;
        this.isSelect = isSelect;
        this.shiftId = shiftId;
        this.deviceSn = deviceSn;
        this.idAndDeviceSn = deptId + "-" + deviceSn;
    }

    public long getDeptId() {
        return deptId;
    }

    public void setDeptId(long deptId) {
        this.deptId = deptId;
        refreashIdAndDeviceSn();
    }

    public String getDeptName() {
        return deptName;
    }

    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    public boolean getIsSelect() {
        return isSelect;
    }

    public void setIsSelect(boolean isSelect) {
        this.isSelect = isSelect;
    }

    public int getShiftId() {
        return shiftId;
    }

    public void setShiftId(int shiftId) {
        this.shiftId = shiftId;
    }

    public String getDeviceSn() {
        return deviceSn;
    }

    public void setDeviceSn(String deviceSn) {
        this.deviceSn = deviceSn;
        refreashIdAndDeviceSn();
    }

    public String getIdAndDeviceSn() {
        return idAndDeviceSn;
    }

    public void setIdAndDeviceSn(String idAndDeviceSn) {
        this.idAndDeviceSn = idAndDeviceSn;
    }

    public void refreashIdAndDeviceSn() {
        this.idAndDeviceSn = deptId + "-" + deviceSn;
    }
    // KEEP METHODS - put your custom methods here

    @Override
    public String toString() {
        return "ScheduleDepartment{" +
                "deptId=" + deptId +
                ", deptName='" + deptName + '\'' +
                ", shiftId=" + shiftId +
                ", deviceSn=" + deviceSn +
                '}';
    }

    @Override
    public void setName(String name) {
        deptName = name;
    }

    @Override
    public String getName() {
        return deptName;
    }

    public boolean isSelect() {
        return isSelect;
    }

    public void setSelect(boolean select) {
        isSelect = select;
    }
}
