package com.example.timeassistant.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here

import android.net.wifi.WifiInfo;

import com.litesuits.orm.db.annotation.Column;
import com.litesuits.orm.db.annotation.PrimaryKey;
import com.litesuits.orm.db.annotation.Table;
import com.litesuits.orm.db.annotation.Unique;
import com.litesuits.orm.db.enums.AssignType;

/**
 * Entity mapped to table "UU_DEVICE".
 */
@Table("UuDevice")
public class UuDevice implements java.io.Serializable {

    //WEKEID
    public static final String COL_DEVICESN = "deviceSn";
    public static final String COL_SSID = "SSID";
    public static final String COL_BSSID = "BSSID";
    public static final String COL_networkId = "networkId";
    public static final String COL_wifiPwd = "wifiPwd";
    public static final String COL_aliases = "aliases";
    public static final String COL_isUuDevice = "isUuDevice";
    public static final String COL_bindHwId = "bindHwId";
    public static final String COL_bindPin = "bindPin";
    public static final String COL_bindName = "bindName";
    public static final String COL_bindPwd = "bindPwd";
    public static final String COL_right = "right";
    public static final String COL_ipAddr = "ipAddr";
    public static final String COL_udkPwd = "udkPwd";
    public static final String COL_udkPort = "udkPort";
    public static final String COL_LANUAGE = "lanuage";

    @PrimaryKey(AssignType.BY_MYSELF)
    @Column(COL_DEVICESN)
    @Unique
    private String deviceSn;                //获取 设备名-序列号 作为唯一标示
    @Column(COL_SSID)
    private String SSID;            //
    @Column(COL_BSSID)
    private String BSSID;           //路由器的mac地址
    @Column(COL_networkId)
    private int networkId;
    @Column(COL_wifiPwd)
    private String wifiPwd;
    @Column(COL_aliases)
    private String aliases;
    @Column(COL_isUuDevice)
    private Boolean isUuDevice;
    @Column(COL_bindHwId)
    private String bindHwId;
    @Column(COL_bindPin)
    private String bindPin;
    @Column(COL_bindName)
    private String bindName;
    @Column(COL_bindPwd)
    private String bindPwd;
    @Column(COL_right)
    private int right;
    @Column(COL_ipAddr)
    private String ipAddr;
    @Column(COL_udkPwd)
    private String udkPwd;
    @Column(COL_udkPort)
    private int udkPort;
    @Column(COL_LANUAGE)
    private String lanuage;

    // KEEP FIELDS - put your custom fields here
    public static final String TAG = "UuDevice";
    // KEEP FIELDS END

    public UuDevice() {
    }

    public UuDevice(String BSSID) {
        this.BSSID = BSSID;
    }

    public UuDevice(String SSID, String BSSID, int networkId, String wifiPwd, String aliases, Boolean isUuDevice, String bindHwId, String bindPin, String bindName, String bindPwd, int right, String ipAddr, String udkPwd, int udkPort) {
        this.SSID = SSID;
        this.BSSID = BSSID;
        this.networkId = networkId;
        this.wifiPwd = wifiPwd;
        this.aliases = aliases;
        this.isUuDevice = isUuDevice;
        this.bindHwId = bindHwId;
        this.bindPin = bindPin;
        this.bindName = bindName;
        this.bindPwd = bindPwd;
        this.right = right;
        this.ipAddr = ipAddr;
        this.udkPwd = udkPwd;
        this.udkPort = udkPort;
    }

    public String getDeviceSn() {
        return deviceSn;
    }

    public void setDeviceSn(String deviceSn) {
        this.deviceSn = deviceSn;
    }


    public String getSSID() {
        return SSID;
    }

    public void setSSID(String SSID) {
        this.SSID = SSID;
    }

    public String getBSSID() {
        return BSSID;
    }

    public void setBSSID(String BSSID) {
        this.BSSID = BSSID;
    }

    public int getNetworkId() {
        return networkId;
    }

    public void setNetworkId(int networkId) {
        this.networkId = networkId;
    }

    public String getWifiPwd() {
        return wifiPwd;
    }

    public void setWifiPwd(String wifiPwd) {
        this.wifiPwd = wifiPwd;
    }

    public String getAliases() {
        return aliases;
    }

    public void setAliases(String aliases) {
        this.aliases = aliases;
    }

    public Boolean getIsUuDevice() {
        return isUuDevice;
    }

    public void setIsUuDevice(Boolean isUuDevice) {
        this.isUuDevice = isUuDevice;
    }

    public String getBindHwId() {
        return bindHwId;
    }

    public void setBindHwId(String bindHwId) {
        this.bindHwId = bindHwId;
    }

    public String getBindPin() {
        return bindPin;
    }

    public void setBindPin(String bindPin) {
        this.bindPin = bindPin;
    }

    public String getBindName() {
        return bindName;
    }

    public void setBindName(String bindName) {
        this.bindName = bindName;
    }

    public String getBindPwd() {
        return bindPwd;
    }

    public void setBindPwd(String bindPwd) {
        this.bindPwd = bindPwd;
    }

    public int getRight() {
        return right;
    }

    public void setRight(int right) {
        this.right = right;
    }

    public String getIpAddr() {
        return ipAddr;
    }

    public void setIpAddr(String ipAddr) {
        this.ipAddr = ipAddr;
    }

    public String getUdkPwd() {
        return udkPwd;
    }

    public void setUdkPwd(String udkPwd) {
        this.udkPwd = udkPwd;
    }

    public int getUdkPort() {
        return udkPort;
    }

    public void setUdkPort(int udkPort) {
        this.udkPort = udkPort;
    }

    public String getLanuage() {
        return lanuage;
    }

    public void setLanuage(String lanuage) {
        this.lanuage = lanuage;
    }

// KEEP METHODS - put your custom methods here


    @Override
    public String toString() {
        return "UuDevice{" +
                "deviceSn='" + deviceSn + '\'' +
                "SSID='" + SSID + '\'' +
                ", BSSID='" + BSSID + '\'' +
                ", networkId=" + networkId +
                ", wifiPwd='" + wifiPwd + '\'' +
                ", aliases='" + aliases + '\'' +
                ", isUuDevice=" + isUuDevice +
                ", bindHwId='" + bindHwId + '\'' +
                ", bindPin='" + bindPin + '\'' +
                ", bindName='" + bindName + '\'' +
                ", bindPwd='" + bindPwd + '\'' +
                ", right=" + right +
                ", ipAddr='" + ipAddr + '\'' +
                ", udkPwd='" + udkPwd + '\'' +
                ", udkPort=" + udkPort +
                '}';
    }

    public UuDevice(WifiInfo info) {
        if (info == null) return;
        SSID = info.getSSID() == null ? "" : info.getSSID().replace("\"", "");
        BSSID = info.getBSSID() == null ? "" : info.getBSSID();
        networkId = info.getNetworkId();
    }

    public boolean isAdmin() {
        return right == 1;
    }

    public boolean isUnbind() {
        return bindPin == null || bindPin.length() == 0;
    }
    // KEEP METHODS END

}
